
name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the node version your project requires
    - run: npm install
    - run: npm run build
    - run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REACT_APP_ENV: 'production'  # Set any environment variables you need for building your project
